# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c87cd415d3ba1478441b0ca6a7647b8f7e6878a310cbff087adfa040542bbad6f17a4ec10fb46383da4d794043a8d236416568ff7a67b5421c6e02d5a344367

test:
  secret_key_base: ff6922760e0efeba328ea655fec4d9e2b73d18601de22c2d44c6b33bbc4b91ca3c3e9887cf15c0022b07050061ffa05bbfed912ee777992b10a90ccc9319b555

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
